JovemProgramadorMvc/Models/AlunoModel.cs
namespace JovemProgramadorMvc.Models
{
    public class AlunoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Contato { get; set; }
        public string Email { get; set; }
        public string Cep { get; set; }
    }
}

JovemProgramadorMvc/Models/EnderecoModel.cs
namespace JovemProgramadorMvc.Models
{
    public class EnderecoModel
    {
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string localidade { get; set; }
        public string uf { get; set; }
        public string ddd { get; set; }
    }
}

JovemProgramadorMvc/Models/ErrorViewModel.cs
using System;

namespace JovemProgramadorMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JovemProgramadorMvc/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using JovemProgramadorMvc.Data.Repositorio.Interfaces;
using JovemProgramadorMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace JovemProgramadorMvc.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IAlunoRepositorio _alunoRepository;
        public AlunoController(IConfiguration configuration, IAlunoRepositorio alunoRepository)
        {
            _configuration = configuration;
            _alunoRepository = alunoRepository;
        }

        public IActionResult Index()
        {
            var alunos = _alunoRepository.BuscarAlunos();

            return View(alunos);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public async Task<IActionResult> BuscarEndereco(string cep)
        {
            var enderecoModel = new EnderecoModel();

            try
            {
                cep = cep.Replace("-", "");

                using var client = new HttpClient();
                var route = $"{_configuration.GetSection("ApiCep")["BaseUrl"]}{cep}/json";
                var result = await client.GetAsync(route);

                if (result.IsSuccessStatusCode)
                {
                    var content = await result.Content.ReadAsStringAsync();
                    enderecoModel = JsonSerializer.Deserialize<EnderecoModel>(content, new JsonSerializerOptions());

                    if (string.IsNullOrEmpty(enderecoModel.complemento))
                    {
                        enderecoModel.complemento = "Nenhum";
                    }                    
                }
                else
                {
                    ViewData["Mensagem"] = "Erro na busca do endereço!";
                    return View();
                }

            }
            catch (Exception ex)
            {
                ViewData["Mensagem"] = $"Erro na busca do endereço! Mensagem: {ex.Message}";
                throw;
            }

            return View("BuscarEndereco", enderecoModel);
        }

        [HttpPost]
        public IActionResult InserirAsync(AlunoModel aluno)
        {
            var sucesso = _alunoRepository.Inserir(aluno);

            if (!sucesso)
            {
                ViewData["MensagemErro"] = "Houve um erro ao cadastrar o aluno, verifique!";
                return View();
            }
            
            ViewData["MensagemSucesso"] = "Aluno cadastrado com sucesso!";
            
            return RedirectToAction("Index", ViewData["MensagemSucesso"]);
        }
    }
}

JovemProgramadorMvc/Controllers/ConhecimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMvc.Controllers
{
    public class ConhecimentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using JovemProgramadorMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace JovemProgramadorMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JovemProgramadorMvc/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMvc.Controllers
{
    public class ProfessorController : Controller
    {
        public ProfessorController()
        {

        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMvc/Views/Aluno/Adicionar.cshtml
@model AlunoModel

<form class="form-horizontal" asp-controller="Aluno" asp-action="Inserir" method="post">
    <fieldset>
        <div class="panel panel-primary">
            <div class="panel-heading">Cadastro de Alunos</div>
            <div class="panel-body">

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-1 control-label" for="Nome">Nome</label>
                    <div class="col-md-8">
                        <input id="Nome" placeholder="Digite seu nome" class="form-control input-md" required="" type="text" asp-for="Nome">
                    </div>
                </div>

                <!-- Text input-->
                <label class="col-md-1 control-label" for="Idade">Idade</label>
                <div class="col-md-2">
                    <input id="idade" placeholder="Digite sua idade" class="form-control input-md" required="" type="text" asp-for="Idade" maxlength="10" onBlur="showhide()">
                </div>

                <!-- Text input-->
                <label class="col-md-1 control-label" for="telefone">Telefone</label>
                <div class="col-md-2">
                    <input id="contato" placeholder="Digite seu telefone" class="form-control input-md" required="" type="text" asp-for="Contato" maxlength="10" onBlur="showhide()">
                </div>

                <!-- Prepended text-->
                <div class="form-group">
                    <label class="col-md-2 control-label" for="prependedtext">Email</label>
                    <div class="col-md-5">
                        <div class="input-group">
                            <input id="prependedtext" class="form-control" placeholder="email@email.com" required="" type="text" asp-for="Email">
                        </div>
                    </div>
                </div>

                <label class="col-md-1 control-label" for="Idade">Cep</label>
                <div class="col-md-2">
                    <input id="cep" placeholder="Digite seu cep" class="form-control input-md" required="" type="text" asp-for="Cep" maxlength="10" onBlur="showhide()">
                </div>

                <!-- Button (Double) -->
                <div class="form-group">
                    <label class="col-md-2 control-label" for="Cadastrar"></label>
                    <div class="col-md-8">
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                        <a type="button" class="btn btn-danger" asp-controller="Aluno" asp-action="Index">Cancelar</a>
                    </div>
                </div>

            </div>
        </div>
    </fieldset>
</form>

JovemProgramadorMvc/Views/Aluno/BuscarEndereco.cshtml
@if (ViewData["Mensagem"] != null)
{
    <div class="alert-danger">
        @ViewData["Mensagem"]
    </div>
}

@model EnderecoModel
<form>
    <div class="mb-3">
        <label for="name" class="form-label">Logradouro</label> <input type="text" class="form-control col-md-6" asp-for="logradouro">
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Complemento</label> <input type="text" class="form-control col-md-4" asp-for="complemento">
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Bairro</label> <input type="text" class="form-control col-md-6" asp-for="bairro" />
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Localidade</label> <input type="text" class="form-control col-md-6" asp-for="localidade" />
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Uf</label>
        <input type="text" class="form-control col-md-1" asp-for="uf">
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">DDD</label>
        <input type="text" class="form-control col-md-1" asp-for="ddd">
    </div>
    <a type="button" class="btn btn-primary" asp-controller="Aluno" asp-action="Index">Voltar</a>
</form>

JovemProgramadorMvc/Views/Aluno/Index.cshtml
@model List<AlunoModel>

@if (ViewData["Mensagem"] != null)
{
    <div class="alert-danger">
        @ViewData["Mensagem"]
    </div>
}

@if (ViewData["MensagemSucesso"] != null)
{
    <div class="alert-success">
        @ViewData["MensagemSucesso"]
    </div>
}

<div>
    <h1>
        Dados dos alunos
    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Idade</th>
                <th scope="col">Contato</th>
                <th scope="col">E-mail</th>
                <th scope="col">Cep</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var aluno in Model)
                {
                    <tr>
                        <th scope="row">@aluno.Id</th>
                        <td>@aluno.Nome</td>
                        <td>@aluno.Idade</td>
                        <td>@aluno.Contato</td>
                        <td>@aluno.Email</td>
                        <td>@aluno.Cep</td>
                        <td>
                            <a type="button" class="btn btn-primary" asp-controller="Aluno" asp-action="BuscarEndereco" asp-route-cep=@aluno.Cep>Endereço</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="text-center">
        <a href="@Url.Action("Adicionar", "Aluno")" class="btn btn-primary">
            Adicionar Novo Aluno
        </a>
    </div>

</div>

JovemProgramadorMvc/Views/Conhecimento/Index.cshtml
<div class="text-center">
    <h1 class="display-4">
        Conteúdos Administrados</hl>
        <a href="https://www.google.com.br/">Google</a>
</div>

JovemProgramadorMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Bem vindo aluno(a)";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo aluno(a)</h1>
    <p>Escreva aqui sobre o curso.</p>
</div>

JovemProgramadorMvc/Views/Professor/Index.cshtml
<div>
    <h1>
        Dados da professora
    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Idade</th>
                <th scope="col">Contato</th>
                <th scope="col">E-mail</th>
                <th scope="col">Cep</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Katia Schimitt Pollheim</td>
                <td>28 anos</td>
                <td>(47) 9911774897</td>
                <td>katiaschimittp@gmail.com</td>
                <td>88350-665</td>
                <td>
                    <button type="button" class="btn btn-primary">Endereço</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

JovemProgramadorMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jovem Programador MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jovem Programador Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Professor(a)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conhecimento" asp-action="Index">Conhecimentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JovemProgramadorMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>